### ISSUE TITLE
Zooming in and out changes the node size.

### ISSUE THREAD

**Issue by kratochvil-jan** [rokups/ImNodes#15]
Zooming in and out changes the node size.
![Screenshot from 2019-12-25 16-20-02](https://user-images.githubusercontent.com/12199298/71447726-89162780-2732-11ea-92e8-3bdd7f07a361.png)

**Comment by sphaero** [comment]
Isn't this a duplicate of #10

**Comment by rokups** [comment]
Indeed it is. :pray:
