### ISSUE TITLE
Connection remaining after the node has beed deleted

### ISSUE THREAD

**Issue by KonstantinVeljanovski** [rokups/ImNodes#2]
Hello,

I found a bug where the connection remains even after the node has been deleted.
Example:
![image](https://user-images.githubusercontent.com/47033144/59765535-94c5f480-929e-11e9-84c0-9edd4af20a42.png)

Any action after that causes a crash.

**Comment by rokups** [comment]
You are in charge of rendering connections. Do not call `ImNodes::Connection()` when one of the nodes is missing.
