### ISSUE TITLE
Support for highlight around Node

### ISSUE THREAD

**Issue by flamendless** [rokups/ImNodes#33]
Hi, I got really far now in my project using this lib. Thanks!

Now I'm wondering if ImNodes will have the "highlight" around the border of the node? kind of like a glow. My use case is that whenever I am to move the canvas' camera offset to a certain node (using find), i want to give a feedback to the user to signify that this is the node that's found.

**Comment by rokups** [comment]
Not out if the box, but you could render render something around the node manually through `ImGui::GetWindowDrawList()`. You can get node rect by calling `ImGui::GetItemRectMin()`/`ImGui::GetItemRectMax()` after `EndNode()`.

**Comment by flamendless** [comment]
Thanks! It works
