### ISSUE TITLE
Change `assert` macro to `IM_ASSERT`

### ISSUE THREAD

**Issue by DenSinH** [rokups/ImNodes#35]
I want to use this module in a project of mine, but I defined my own `IM_ASSERT`. ImNodes seems to just use `assert` from `<assert.h>`, but I think it would make more sense if it would also use `IM_ASSERT`, like the rest of ImGui. The fix should be easy, I was able to literally find and replace `assert` by `IM_ASSERT` in `ImNodes.cpp`.

**Comment by rokups** [comment]
Sure thing 👍🏻
