### ISSUE TITLE
Hitting delete with inactive Canvas deletes selected node

### ISSUE THREAD

**Issue by sphaero** [rokups/ImNodes#38]
Just try the sample.cpp application:
* Make sure a node is selectedl
* Then select the Hello world windows
* Hit the delete key 
* Notice the selected node gets deleted

**Comment by sphaero** [comment]
This seems a trivial problem to fix but I have not found the right code yet to skip the delete if the window is not active/hovered/nav???/selected

**Comment by sphaero** [comment]
related code: https://github.com/rokups/ImNodes/blob/581525381beb5fa26dd46e9ea42216d4dbbff5c7/sample.cpp#L177

**Comment by sphaero** [comment]
`if (node->Selected && ImGui::IsKeyPressedMap(ImGuiKey_Delete) && ImGui::IsWindowFocused())`

Seems a solution but it feels like this should be done differently? Anyone?

**Comment by rokups** [comment]
Looks good to me.

**Comment by sphaero** [comment]
I'll create a PR. However it feels like this should be handled automatically somehow. I've not experienced this with builtin widgets and windows.

**Comment by rokups** [comment]
Widgets do not handle key presses, user application does. This is why its in sample.cpp.
