### ISSUE TITLE
Can only select nodes with rectangle select

### ISSUE THREAD

**Issue by sphaero** [rokups/ImNodes#6]
Any reason why a node is not selectable by just clicking on it? The only way now is by using the rectangle select.

**Comment by rokups** [comment]
They were selectable by clicking at some point. Must be a bug :]

**Comment by sphaero** [comment]
It might have to do with:
https://github.com/rokups/ImNodes/blob/e3431ce8bad2d68e52f728edd14aebaac7e8727b/ImNodes.cpp#L473

IsAnyItemActive always returns true at that specific moment, removing the exclamation does make it selectable by click again. I'm just not sure why there was IsAnyItemActive test in the first place.
