### ISSUE TITLE
Cmake report error on Windows platform

### ISSUE THREAD

**Issue by ychding11** [rokups/ImNodes#8]
```
CMake Error at C:/Program Files/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindPkgConfig.cmake:39 (find_package_handle_standard_args)
  CMakeLists.txt:28 (find_package)
```

**Comment by rokups** [comment]
Build on Windows is not supported yet. It's only for a sample though, if 
you included ImNodes source files into your project no reason it won't work.

**Comment by ychding11** [comment]
Thanks for reply.
Have you test in on windows with D3D ? I found your sample is with OpenGL.
Thanks!

**Comment by rokups** [comment]
I did not test it with D3D, but like i said there is no reason why it would not work. ImGui works with D3D and so will ImNodes :]

**Comment by ychding11** [comment]
I just test it. it works on Windows 10 D3D11.
great job.
